//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQLBanHangEntities : DbContext
    {
        public DBQLBanHangEntities()
            : base("name=DBQLBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBill> tblBills { get; set; }
        public DbSet<tblCustumer> tblCustumers { get; set; }
        public DbSet<tblDetailBill> tblDetailBills { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblStaff> tblStaffs { get; set; }
        public DbSet<tblStyle> tblStyles { get; set; }
        public DbSet<tblSupplierProduct> tblSupplierProducts { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
