//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblDetailBills = new HashSet<tblDetailBill>();
        }
    
        public int ID { get; set; }
        public string codeProduct { get; set; }
        public string nameProduct { get; set; }
        public string descriptionProduct { get; set; }
        public Nullable<int> idSup { get; set; }
        public Nullable<int> quantityProductInput { get; set; }
        public Nullable<double> priceProductInput { get; set; }
        public string colorPro { get; set; }
        public string sizePro { get; set; }
        public string material { get; set; }
        public string genderUse { get; set; }
        public Nullable<int> IDStyle { get; set; }
        public string imageProduct1 { get; set; }
        public string imageProduct2 { get; set; }
        public string imageProduct3 { get; set; }
    
        public virtual ICollection<tblDetailBill> tblDetailBills { get; set; }
        public virtual tblStyle tblStyle { get; set; }
        public virtual tblSupplierProduct tblSupplierProduct { get; set; }
    }
}
