//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierProduct
    {
        public tblSupplierProduct()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int idSup { get; set; }
        public string supplierName { get; set; }
    
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
