//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaff
    {
        public tblStaff()
        {
            this.tblBills = new HashSet<tblBill>();
        }
    
        public int IDStaff { get; set; }
        public string StaffName { get; set; }
    
        public virtual ICollection<tblBill> tblBills { get; set; }
    }
}
